version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - $HOME/projpgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4
    expose:
      - "80"
    ports:
      - "5454:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost
      PGADMIN_DEFAULT_PASSWORD: postgres
  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
